### PR TITLE
feat: add custom header key support to EventSource API

### PR DESCRIPTION
**Pull request by esmadrider**
Solved https://github.com/Lusito/react-nano/issues/1.

Thanks to @RunDevelopment and @Lusito help me write these codes in:

* https://github.com/Lusito/react-nano/issues/1
* https://github.com/chaiNNer-org/chaiNNer/issues/1798

Even if the official [EventSource API - MDN Page](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) doesn't support custom header keys, for now, we can use [event-source-polyfill](https://www.npmjs.com/package/event-source-polyfill) to customize in [@react-nano/use-event-source](https://www.npmjs.com/package/@hyler-coop/use-event-source) just using `createESClassWithHeaders` function.

With no breaking changes, It feels so cool to make this contribution.

Feel free to merge this pull request or not. I have already published the downstream version to NPM: https://www.npmjs.com/package/@hyler-coop/use-event-source. But looking forward to make react-nano be better together.

### CODE REVIEW

**Comment by RunDevelopment** [comment]
React nano probably should not add `event-source-polyfill` as a dependency, given that the first sentence in the README of that library is:

> Пожалуйста не используйте эту обосранную библиотеку!

which Google Translate says is:

> Please do not use this crap library!

There is also an issue about this line: https://github.com/Yaffle/EventSource/issues/213

This library also seems to have been the target/source of a supply chain attack: https://github.com/Yaffle/EventSource/issues/202. There's also https://github.com/Yaffle/EventSource/issues/199.

While software can be used an expression of free speech and a political statement, I would be careful with using such software.

**Comment by esmadrider** [comment]
> Пожалуйста не используйте эту обосранную библиотеку!

Sorry for not considering these before. If @Lusito also thinks `event-source-polyfill` is not appropriate, we can close this PR.

https://github.com/Azure/fetch-event-source

And I found another lib maybe can do the same thing, I can try to make another PR.

**Comment by Lusito** [comment]
First of all, I appreciate the effort to make a contribution. I'm not going to accept the PR for several reasons. I'll give you some explanations, so you understand it and are aware in case of another PR:

#### The polyfill

As @RunDevelopment already said, the library is a bit sketchy.

Even if it was completely trustworthy: A lot of users probably don't want to use the polyfill and with this PR, you are forcing them to download it anyway, as you've listed it as a dependency. Having it as a dependency also means, that I have to maintain the version number and make sure that there are no security issues with new versions.

A better approach would be to list it as a peerDependency. That way, the user doesn't need to install it unless they use the code that depends on it. In that case, the function createESClassWithHeaders should be defined in a separate file, so that one could do `import { createESClassWithHeaders } from '@react-nano/use-event-source/with-polyfill'` or something similar.

Alternatively, you could do it in a similar way as I did with `EventSourceConstructor`. I.e. define a constructor type, which accepts both `withCredentials` and `headers`. That way, no modification of the package.json would be required. Of course, the user would have to pass in the EventSourcePolyfill to the createESClassWithHeaders function for that to work.

#### Missing documentation

If I would accept a PR, which added new functionality, it should also modify the [documentation](https://lusito.github.io/react-nano/use-event-source/), as otherwise people won't know it's there.

#### The package.json version

The version number is usually bumped up during the release and not during the feature pull requests. You can leave that work up to the maintainers of the library.

#### About fetch-event-source

That library has a different API (no classes, different listeners, ...), so there would have to be modifications to useEventSource.

#### A safer approach

I would not consider any of these approaches a best-practice, but rather a last-resort. What I could accept, would be to extend the readme with some information for those who have no other choice. But that choice should be well-informed, so a link to #1 would be mandatory (and reduce the required text in the readme).

**Comment by esmadrider** [comment]
OK, it's clear that we don't need this PR now.

My situation about injecting headers to EventSource API is in such uncommon usage, it's not necessary to make many modifications to this repo.

The other people who want to add header support will be led to this PR  and issue #1 by search engines, they will know what happened. So it's also not necessary for me to make another PR.

Let me close this PR and thanks for all your work and sharing!

**Pull request closed without merging**
